language: java

jdk:
  - oraclejdk11

# see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: true

before_install:
  - sudo add-apt-repository ppa:cwchien/gradle
  - sudo apt-get update
  - sudo apt -y sudo apt upgrade gradle

