language: java

jdk:
  - oraclejdk11

# see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false

before_install:
  gradle wrapper
  ./gradlew wrapper --gradle-version 5.3

